### ISSUE TITLE
[FEAT] 도메인 구현

### ISSUE THREAD

**Issue by ChaeAg** [Team-WSS/WSS-Server-AppJam#1]
## Description
프로젝트에 사용될 도메인 구현

## To-Do
- [x] `Keyword` 도메인 구현
- [x] `User` 도메인 구현
- [x] `Character` 도메인 구현
- [x] `Platform` 도메인 구현
- [x] `Novel` 도메인 구현
- [x] `Memo` 도메인 구현
- [x] `UserNovel` 도메인 구현
- [x] `UserNovelKeyword` 도메인 구현
- [x] `UserCharacter` 도메인 구현

## Reference
X
