### ISSUE TITLE
[FEAT] 유저 닉네임 변경 API 구현

### ISSUE THREAD

**Issue by ChaeAg** [Team-WSS/WSS-Server-AppJam#24]
## Description
변경할 닉네임을 Request Body로 받아, 현재 로그인 한 유저의 닉네임을 변경하는 API 구현

## To-Do
- [x] 유저 닉네임 변경 API 구현
- [x] 닉네임 변경 시 jwt 재발급
- [x] 닉네임 최대 길이 10자 제한

## Reference
X
