### ISSUE TITLE
[FEAT] 요구사항 추가에 따른 도메인 수정 및 추가

### ISSUE THREAD

**Issue by Kim-TaeUk** [Team-WSS/WSS-Server-AppJam#37]
## Description
프로젝트 요구사항이 변경/추가되어 사용될 Avatar, User, UserAvatar, AvatarLine, GenreBadge 도메인 수정 및 구현
## To-Do
- [x] `Avatar` 도메인 수정
- [x] `User` 도메인 수정
- [x] `UserAvatar` 도메인 수정
- [x] `AvatarLine` 도메인 추가
- [x] `GenreBadge` 도메인 추가
