### ISSUE TITLE
[REFACTOR] 서버 파트장 프로젝트 피드백 반영

### ISSUE THREAD

**Issue by Kim-TaeUk** [Team-WSS/WSS-Server-AppJam#75]
## Description
서버 파트장 피드백 반영

## To-Do
- [x] path variable 사용 시 앞에 `/` 명시해주기
- [x] 메모 작성 API 엔드포인트 변경(`/memos/{userNovelId}` -> `/user-novels/{userNovelId}/memo`)
- [x] 유저 정보 조회 API 엔드포인트 변경(`/users/user-info` -> `/users/info`)
- [x] NPE 방지를 위해 주인 entity에서 연관된 Collection field 명시적 초기화
- [x] `@Transactional` 어노테이션(+ readOnly 옵션) 누락된 부분 해결 
- [x] DTO 별도 패키지로 분리
- [x] 누락된 `@Repository` 어노테이션 추가
- [x] User 엔티티 `userName` 컬럼 추가
- [x] 엔티티에 @NoArgsConstructor(access = AccessLevel.PROTECTED) 누락된 부분 추가
- [x] DTO의 JSON Array 네이밍 -List 대신 복수형(-s)으로 변경
